project:
  type: website
  output-dir: docs

website:
  title: "Cash Looi"   # this becomes the "Home" link
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: conference.qmd
        text: Conference

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

